#!/bin/sh

[ "$ACTION" = add ] || exit 0
[ -n "$DEVPATH" ] || exit 0

sys="/sys$DEVPATH"
devname="${DEVNAME:-${DEVPATH##*/}}"
[ -n "$devname" ] || exit 0
name="$(cat "$sys/name" 2>/dev/null)"
case "$name" in
DATA5_CNTL) ln -snf "/dev/$devname" /dev/modem ;;
DATA4) ln -snf "/dev/$devname" /dev/modem-at ;;
esac

case "$devname" in
rpmsg_ctrl*)
	/usr/sbin/rpmsgexport "/dev/$devname" DATA5_CNTL
	/usr/sbin/rpmsgexport "/dev/$devname" DATA4
	;;
esac
